curso_dbt_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      # arquivo do banco duckdb dentro do próprio diretório de trabalho /usr/app
      path: /usr/app/curso_dbt_duckdb.duckdb
      threads: 1
      schema: main
      extensions:
        - parquet
        - json


